### ISSUE TITLE
ffmpegがPATHに存在しないときに正常に動作しない。

### ISSUE THREAD

**Issue by cat-love-7** [m-hayabusa/VRCImageHelper#18]
ほかに報告がないので私の環境依存の問題かもしれませんが、下の挙動が見つかりました。

ffmpegがPATHに存在しない場合に使用する実行ファイルが./ffmpeg/ffmpeg.exeになっていますが、ダウンロードした際に実行ファイルが作成されるのは./ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exeでした。
そのため、ffmpegが存在しないと誤認してffmpegを再度ダウンロードしようとします。

**Comment by m-hayabusa** [comment]
https://github.com/m-hayabusa/VRCImageHelper/commit/cdf0a5b092f9ba632168cad1f9c1cb8f719b7193#diff-415607c886a1abb86735dd35f44fc220003c99b1be4d8b7b0bc109ef70493ca2L71-L83 
で壊してしまっていました 修正します
