### ISSUE TITLE
PNG形式で保存したとき、Adobe製品で適切に日付が認識されない

### ISSUE THREAD

**Issue by m-hayabusa** [m-hayabusa/VRCImageHelper#2]
必要なのは https://exiftool.org/TagNames/XMP.html#photoshop の Photoshop:DateCreated あたりだろうか？

**Comment by m-hayabusa** [comment]
Photoshop:DateCreatedは書きこめなかった、 #6 でもまだ動かないようだ

**Comment by cat-love-7** [comment]
> Photoshop:DateCreatedは書きこめなかった

xmp-Photoshop:DateCreatedで書き込めると思います。

**Comment by m-hayabusa** [comment]
書き込めたようです ありがとうございます
ただ、自分自身はAdobe製品を持っていないのでこれ以上の確認ができず…

**Comment by cat-love-7** [comment]
xmp-Photoshop:DateCreatedとDateCreatedで違う日付を入力したところ、Lightroomではxmp-Photoshop:DateCreated側の日付で認識されたので問題なさそうです。
