### ISSUE TITLE
エンコーダにav1_nvencを使用した際の動作不良について

### ISSUE THREAD

**Issue by amanao** [m-hayabusa/VRCImageHelper#40]
日頃から有難く使用させて頂いております。

NVEncについての情報です。
https://github.com/m-hayabusa/VRCImageHelper/blob/dfc5d15e0ae3f341d8aecc3786c2125d6ad0d14c/README.md?plain=1#L58

既存のソフトウェアのまま実行すると下記のエラーが出力されます。
```
[av1_nvenc @ 000002359af29040] YUV444P not supported
[av1_nvenc @ 000002359af29040] No capable devices found
```
これはav1_nvencがYUV444Pに対応していない事に起因する問題のようです。
`-pix_fmt yuv420p`オプションを付けることで実行は可能ですが、情報量が下がってしまうため、推奨は出来ません。

よろしくお願いいたします。

**Comment by m-hayabusa** [comment]
報告ありがとうございます。
readmeにダウンサンプルされることを書いた上で、該当のオプションをデフォルトで付けることとしようと思います。
