### ISSUE TITLE
VRChatのログファイルのサイズが非常に大きいとSystem.OutOfMemoryExceptionが発生する

### ISSUE THREAD

**Issue by cat-love-7** [m-hayabusa/VRCImageHelper#9]
最後に作成されたoutput_log_*.txtファイルの容量が大きいと起動時に[VRCImageHelper/Core/LogReader.cs:127](https://github.com/m-hayabusa/VRCImageHelper/blob/c0a4b3dc9af3bb98d9d69d520bfa81e309eaf076/VRCImageHelper/Core/LogReader.cs#L127)でSystem.OutOfMemoryExceptionが発生する。
私の環境ではアバターの不具合でログファイルが1.1GBになった状態で発生しました。

**Comment by m-hayabusa** [comment]
ReadLineで各行ごと処理するように変更してみます (行単位でもOOMとなった場合は捨ててしまうこととします)
